name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Space
        uses: huggingface/hfaction@v3
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          hf_repo: GGHP/GGHP_APP
          repo_type: space